// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace bookstore_sv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124083441_AddFieldToTableUser")]
    partial class AddFieldToTableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<string>("author_key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("author_key");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isCheckedOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CartItems", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("cart_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("cart_id");

                    b.HasIndex("product_id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("order_id");

                    b.HasIndex("user_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("order_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProductAuthor", b =>
                {
                    b.Property<string>("product_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("author_key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("id")
                        .HasColumnType("longtext");

                    b.HasKey("product_id", "author_key");

                    b.HasIndex("author_key");

                    b.ToTable("ProductAuthors");
                });

            modelBuilder.Entity("ProductCount", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("already_read")
                        .HasColumnType("int");

                    b.Property<int>("currently_reading")
                        .HasColumnType("int");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("want_to_read")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("product_id")
                        .IsUnique();

                    b.ToTable("ProductCounts");
                });

            modelBuilder.Entity("bookstore_sv.Models.Order_Billing_Address", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("order_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("street_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("zip_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.ToTable("Order_Billing_Addresses");
                });

            modelBuilder.Entity("bookstore_sv.Models.Order_Shipping_Address", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("order_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("street_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("zip_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.ToTable("Order_Shipping_Addresses");
                });

            modelBuilder.Entity("bookstore_sv.Models.Product", b =>
                {
                    b.Property<string>("product_id")
                        .HasColumnType("varchar(255)");

                    b.PrimitiveCollection<string>("author_key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cover")
                        .HasColumnType("int");

                    b.Property<string>("cover_edition_key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("first_publish_year")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity_in_stock")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("bookstore_sv.Models.ProductInformation", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("isbn_13")
                        .HasColumnType("longtext");

                    b.Property<int>("number_of_pages")
                        .HasColumnType("int");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("publish_date")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("publishers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("subjects")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("product_id")
                        .IsUnique();

                    b.ToTable("ProductInformations");
                });

            modelBuilder.Entity("bookstore_sv.Models.ProductSummary", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("average")
                        .HasColumnType("float");

                    b.Property<int?>("count")
                        .HasColumnType("int");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("sortable")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("product_id")
                        .IsUnique();

                    b.ToTable("ProductSummaries");
                });

            modelBuilder.Entity("bookstore_sv.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("bookstore_sv.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.HasOne("bookstore_sv.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartItems", b =>
                {
                    b.HasOne("Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("bookstore_sv.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductAuthor", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("ProductAuthors")
                        .HasForeignKey("author_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithMany("ProductAuthors")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductCount", b =>
                {
                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithOne("ProductCount")
                        .HasForeignKey("ProductCount", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("bookstore_sv.Models.Order_Billing_Address", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithOne("Order_Billing_Address")
                        .HasForeignKey("bookstore_sv.Models.Order_Billing_Address", "order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("bookstore_sv.Models.Order_Shipping_Address", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithOne("Order_Shipping_Address")
                        .HasForeignKey("bookstore_sv.Models.Order_Shipping_Address", "order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("bookstore_sv.Models.ProductInformation", b =>
                {
                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithOne("ProductInformation")
                        .HasForeignKey("bookstore_sv.Models.ProductInformation", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("bookstore_sv.Models.ProductSummary", b =>
                {
                    b.HasOne("bookstore_sv.Models.Product", "Product")
                        .WithOne("ProductSummary")
                        .HasForeignKey("bookstore_sv.Models.ProductSummary", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("bookstore_sv.Models.Token", b =>
                {
                    b.HasOne("bookstore_sv.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("ProductAuthors");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Order_Billing_Address");

                    b.Navigation("Order_Shipping_Address");
                });

            modelBuilder.Entity("bookstore_sv.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductAuthors");

                    b.Navigation("ProductCount")
                        .IsRequired();

                    b.Navigation("ProductInformation")
                        .IsRequired();

                    b.Navigation("ProductSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("bookstore_sv.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
